spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bad?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.bad.bigad.entity
jwt_key: rgsnsm#ldyh*ws%l&hdpmnmw@xyhndes
jwt_minute: 360
jwt_pub: bad